# Generated by Django 2.1.7 on 2019-03-29 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField(default=None)),
                ('lng', models.FloatField(default=None)),
                ('timestamp', models.DateTimeField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imo', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='ship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ships.Ship'),
        ),
    ]
