# Generated by Django 2.1.7 on 2019-03-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ships', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='ship_name',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
